# Generated by Django 4.2.6 on 2024-01-08 17:51

from django.db import migrations, models
import phonenumber_field.modelfields
import race.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-имя для мероприятия')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('event_rules', models.TextField(verbose_name='Условия участия')),
                ('event_type', models.CharField(choices=[('trail', 'Трейл'), ('cross', 'Кросс'), ('mountain', 'Горный'), ('road', 'Дорожный')], max_length=50, verbose_name='Тип мероприятия')),
                ('start_datetime', models.DateTimeField(db_index=True, verbose_name='Начало мероприятия')),
                ('total_slots', models.PositiveIntegerField(verbose_name='Всего мест')),
                ('is_upcoming', models.BooleanField(default=True, verbose_name='Предстоящее мероприятие')),
                ('image', models.ImageField(upload_to=race.models.event_image_file_path, verbose_name='Изображение для мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_document', models.FileField(upload_to=race.models.payment_docs_file_path, verbose_name='Документ об оплате')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('club', models.CharField(blank=True, max_length=255, null=True, verbose_name='Клуб')),
                ('tshirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=3, verbose_name='Размер футболки')),
                ('payment_confirmation', models.BooleanField(default=False, verbose_name='Подтверждение оплаты')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная регистрация')),
            ],
            options={
                'verbose_name': 'Регистрация на забег',
                'verbose_name_plural': 'Регистрации на забеги',
            },
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Программа мероприятия',
                'verbose_name_plural': 'Программа мероприятий',
            },
        ),
        migrations.CreateModel(
            name='EventSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Резюме мероприятия')),
                ('file', models.FileField(upload_to=race.models.event_protocol_file_path, verbose_name='Протокол мероприятия')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Резюме для мероприятия',
                'verbose_name_plural': 'Резюме для мероприятий',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to=race.models.event_photos_file_path, verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение для галереи',
                'verbose_name_plural': 'Изображения для галереи',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256, verbose_name='Улица')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Места проведения',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контактные данные')),
                ('payment_details', models.TextField(blank=True, verbose_name='Реквизиты для оплаты')),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.CreateModel(
            name='RaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Муж.'), ('F', 'Жен.')], max_length=1, verbose_name='Пол')),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='Минимальный возраст')),
                ('distance', models.PositiveSmallIntegerField(choices=[(5, '5 км'), (10, '10 км'), (15, '15 км'), (20, '20 км')], verbose_name='Дистанция')),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость регистрации')),
            ],
            options={
                'verbose_name': 'Тип забега',
                'verbose_name_plural': 'Типы забегов',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
