# Generated by Django 4.2.6 on 2023-12-20 17:20

from django.db import migrations, models
import django.db.models.deletion
import race.models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Резюме мероприятия')),
                ('file', models.FileField(upload_to=race.models.event_protocol_file_path, verbose_name='Протокол мероприятия')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Резюме для мероприятия',
                'verbose_name_plural': 'Резюме для мероприятий',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to=race.models.event_photos_file_path, verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение для галереи',
                'verbose_name_plural': 'Изображения для галереи',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to=race.models.event_image_file_path, verbose_name='Изображение для мероприятия'),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='race.event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='eventsummary',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='race.event', verbose_name='Мероприятие'),
        ),
    ]
