# Generated by Django 4.2.6 on 2023-12-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_eventsummary_galleryphoto_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='race.event', verbose_name='Мероприятие'),
        ),
    ]
